apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: {{ .Values.docker.app_image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /
              port: 3000

          livenessProbe:
            httpGet:
              path: /
              port: 3000

          env:
            - name: APP_PORT
              value: '3000'
            - name: ENV
              value: {{ .Values.env }}
            - name: APOS_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: mongodb_uri




      imagePullSecrets:
        - name: {{ .Release.Namespace }}-registry
