apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  database_password: {{ .Values.database_password | quote }}
  mongoURi: mongodb://{{ .Values.database.user }}:{{ .Values.database_password }}@{{ .Release.Name }}-db:{{ .Values.database.port }}/{{ .Values.database.name }}
