apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cms
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-cms
  ports:
      - protocol: TCP
        port: 3000
