apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: 27017
      targetPort: 27017
