name: "Deploy K8s Suite"
description: "Deploys an entire Assets Suite to K8s"
inputs:
  TARGET_ENV:
    description: "The environment to which the chart is deployed."
    required: true
  SUITE_NAME_SUFFIX:
    description: "A suffix added to each chart's name, both in Kubernetes and int the Vault path resolution."
    required: false
    default: ""
  AWS_ROLE:
    description: "The AWS role to assume."
    required: true
  AWS_REGION:
    description: "The AWS region to deploy to."
    required: true

runs:
  using: "composite"
  steps:
    - name: "Setup env"
      shell: bash
      run: echo "SUITE_NAME_SUFFIX=${{ inputs.SUITE_NAME_SUFFIX && format('-{0}', inputs.SUITE_NAME_SUFFIX) }}" >> $GITHUB_ENV
    - name: "Setup kubectl"
      uses: azure/setup-kubectl@v4
    - name: "Install helm"
      uses: azure/setup-helm@v4
    - name: "Configure AWS credentials from AWS account"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.AWS_ROLE }}
        aws-region: ${{ inputs.AWS_REGION }}
        role-session-name: GitHub-OIDC
        retry-max-attempts: 3

    - name: "Deploy landing page"
      uses: ./.github/actions/deploy-k8s-chart
      with:
        TARGET_ENV: ${{ inputs.TARGET_ENV }}
        DEPLOYMENT_NAME: "swissgeol-landingpage${{ env.SUITE_NAME_SUFFIX }}"
        REPO_PATH: ./k8s/swissgeol-landingpage
        VAULT_PATH: "landingpage${{ env.SUITE_NAME_SUFFIX }}"
